### ISSUE TITLE
Render issue with Events on homepage

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#182]
See screenshot:
<img width="474" alt="Screen Shot 2020-03-20 at 10 57 34 PM" src="https://user-images.githubusercontent.com/463160/77176026-71b2c480-6afe-11ea-9247-e088b64da437.png">

**Comment by rodmeurer** [comment]
fixed @cjyabraham 

https://fuerza-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
Ok.  I think there's still a problem on narrow screens:
<img width="569" alt="Screen Shot 2020-03-21 at 10 17 13 AM" src="https://user-images.githubusercontent.com/463160/77217416-5a56f400-6b5d-11ea-9e96-0c32ba4ac6ea.png">
<img width="311" alt="Screen Shot 2020-03-21 at 10 17 01 AM" src="https://user-images.githubusercontent.com/463160/77217419-5e831180-6b5d-11ea-9775-a4e63701891b.png">

**Comment by rodmeurer** [comment]
Sorry for that @cjyabraham, fixed now
https://fuerza-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
Thanks.  Deployed.
